name: Github Actions
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a test. It was triggered by ${{ github.event_name }}."
      - run: echo "Does a bunch of stuff".
      - run: echo "Runs unit tests"
      - run: echo "Builds the Artifact"

